title: Taylor Johnson # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Contact: <a href="mailto:marlaeism6@gmail.com">marlaeism6@gmail.com</a> 
  <br><br>
  Linkedin: <a href="https://www.linkedin.com/in/taylorjohnson12324/">Taylor Johnson</a> 
  <br><br>
  <a href="/cv/">CV</a> <!-- Link to the CV page -->
  <a href="/volunteer/">Volunteer Work</a> <!-- Link to the Volunteer Work page -->
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

github:
  is_project_page: false
